import {skills,connections} from './data/skills.js';
import {projects} from './data/projects.js';
const NS='http://www.w3.org/2000/svg';
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text)n.textContent=text;return n;};
const flow=document.querySelector('#flow-field');
// Decorative coordinate mesh, not a scientific simulation result.
for(let i=0;i<25;i++){const path=document.createElementNS(NS,'path');let d='';for(let j=0;j<=44;j++){let x=35+j*12,y=55+i*15;const influence=Math.exp(-Math.pow((x-295)/140,2));y+=Math.sin((i/24)*Math.PI*2)*105*influence;d+=`${j?'L':'M'}${x},${y} `;}path.setAttribute('d',d);path.setAttribute('fill','none');path.setAttribute('stroke',i%4===0?'#799d8b':'#3c6153');path.setAttribute('stroke-width',i%4===0?'.9':'.5');flow.append(path);}
for(let j=0;j<34;j++){const path=document.createElementNS(NS,'path');let d='';for(let i=0;i<=24;i++){let x=35+j*16,y=55+i*15;y+=Math.sin((i/24)*Math.PI*2)*105*Math.exp(-Math.pow((x-295)/140,2));d+=`${i?'L':'M'}${x},${y} `;}path.setAttribute('d',d);path.setAttribute('fill','none');path.setAttribute('stroke','#3c6153');path.setAttribute('stroke-width','.5');flow.append(path);}
const field=document.querySelector('#project-field');
projects.forEach(p=>{const a=el('a',`project-bubble ${p.size} ${p.status==='Planned'?'planned':''}`);a.href=`project.html?id=${encodeURIComponent(p.id)}`;a.dataset.project=p.id;a.style.left=`${p.position.x}%`;a.style.top=`${p.position.y}%`;a.setAttribute('aria-label',`${p.title} — ${p.status}. View project`);if(p.image){const img=el('img');img.src=p.image;img.alt='';img.loading='lazy';a.append(img);}else{const visual=el('div',`bubble-visual ${p.visual||'grid'}`);visual.setAttribute('aria-hidden','true');a.append(visual);}const copy=el('div','bubble-copy');copy.append(el('span',p.status==='Planned'?'planned-label':'badge',p.status),el('h3','',p.title),el('span','category',p.category),el('p','summary',p.summary),el('span','bubble-arrow','↗'));a.append(copy);field.append(a);});
// Extra projects fall into a normal layout instead of overlapping curated V1 positions.
if(projects.length>3){field.classList.add('expanded-field');const style=document.createElement('style');style.textContent='.expanded-field{display:flex;flex-wrap:wrap;gap:35px;align-items:center;min-height:0}.expanded-field .project-bubble{position:relative!important;left:auto!important;top:auto!important;flex-shrink:0}.expanded-field .featured{width:min(480px,100%)}.expanded-field .medium{width:min(330px,90%)}.expanded-field .small{width:min(260px,80%)}';document.head.append(style);}
const nodes=document.querySelector('#skill-nodes'),lines=document.querySelector('#skill-lines'),detail=document.querySelector('#skill-detail');
connections.forEach(([a,b])=>{const start=skills.find(s=>s.id===a),end=skills.find(s=>s.id===b);if(!start||!end)return;const line=document.createElementNS(NS,'line');line.setAttribute('x1',`${start.x}%`);line.setAttribute('y1',`${start.y}%`);line.setAttribute('x2',`${end.x}%`);line.setAttribute('y2',`${end.y}%`);line.dataset.nodes=`${a} ${b}`;lines.append(line);});
skills.forEach(s=>{const b=el('button','skill-node',s.name);b.type='button';b.dataset.id=s.id;b.style.left=`${s.x}%`;b.style.top=`${s.y}%`;b.setAttribute('aria-pressed','false');b.setAttribute('aria-controls','skill-detail');b.append(el('small','',s.status));b.addEventListener('click',()=>select(s));nodes.append(b);});
function select(s){nodes.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.id===s.id)));lines.querySelectorAll('line').forEach(l=>l.classList.toggle('active',l.dataset.nodes.split(' ').includes(s.id)));detail.replaceChildren(el('span','badge',`${s.role} / ${s.status}`),el('h3','',s.name),el('p','',s.description),el('h4','','Current focus'),el('p','',s.focus));field.querySelectorAll('a').forEach(a=>{const related=s.projects.includes(a.dataset.project);a.classList.toggle('is-related',related);a.classList.toggle('is-muted',!related);});const names=projects.filter(p=>s.projects.includes(p.id)).map(p=>`${p.title}${p.status==='Planned'?' (planned)':''}`).join(', ');document.querySelector('#project-filter-status').textContent=`Connected to ${s.name}: ${names||'No documented project yet'}. All projects remain available.`;}
function reset(){nodes.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed','false'));lines.querySelectorAll('line').forEach(l=>l.classList.remove('active'));field.querySelectorAll('a').forEach(a=>a.classList.remove('is-muted','is-related'));detail.replaceChildren(el('span','badge','An evolving skill map'),el('h3','','Follow a connection.'),el('p','','Select a node to see how it fits into my work and what I’m focusing on next.'),el('h4','','A note on progress'),el('p','','These labels describe my current learning stage. They are not proficiency scores.'));document.querySelector('#project-filter-status').textContent='Explore a project to see the thinking behind it.';}
document.querySelector('#reset-skills').addEventListener('click',reset);reset();document.querySelector('#year').textContent=new Date().getFullYear();
